'use strict';
(()=>{
const $=id=>document.getElementById(id),all=s=>[...document.querySelectorAll(s)];
const reduced=matchMedia('(prefers-reduced-motion: reduce)');
const observer=new IntersectionObserver(entries=>entries.forEach(e=>e.target.classList.toggle('in-view',e.isIntersecting)),{threshold:.12});
const reveal=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.remove('reveal-wait');reveal.unobserve(e.target)}}),{threshold:.1});if(!reduced.matches)all('.section-heading').forEach(el=>{el.classList.add('reveal-wait');reveal.observe(el)});
all('.motion-scene').forEach(el=>observer.observe(el));
all('[data-motion-toggle]').forEach(b=>b.addEventListener('click',()=>{const paused=b.closest('.motion-scene').classList.toggle('motion-paused');b.textContent=paused?'▷':'Ⅱ';b.setAttribute('aria-label',paused?'继续动画':'暂停动画');b.title=paused?'继续动画':'暂停动画'}));
let captured=false;const capturedTypes=new Set();
all('[data-capture]').forEach(b=>b.addEventListener('click',()=>{captured=b.dataset.capture==='on';capturedTypes.clear();all('[data-capture]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));$('evaporation').classList.toggle('is-capturing',captured);$('loss-outcome').textContent=captured?'将流动的信息归档，让每一天都有迹可循。':'信息不断产生，却没有形成可积累的资产。';$('capture-count').textContent=captured?(reduced.matches?'6 类信息已归档':'正在接收…'):'等待捕获';$('evaporation').setAttribute('aria-label',captured?'数据泡泡被捕获，归入个人数据资产':'向日葵生成不同类型的数据泡泡，未捕获时逐渐消失')}));
all('.data-bubble').forEach(b=>b.addEventListener('animationiteration',()=>{if(!captured)return;capturedTypes.add(b.textContent);$('capture-count').textContent=capturedTypes.size+' 类信息已归档'}));
const native={markdown:{file:'2026-06-05.md',status:'现有格式 · 内容示意',code:'# 2026-06-05\n\n## 今日记录\n傍晚散步后，记下了一个新的想法。\n\n## 影像\n![傍晚散步](media/walk.jpg)\n\n## 感受\n走出房间后，注意力重新回到了当下。',description:'开放的文本格式，保留原始表达与媒体引用，可供 Agent 直接读取。'},metadata:{file:'meta.json',status:'现有字段 · 内容示意',code:'{\n  "time_map": {\n    "walk.jpg": "18:20"\n  },\n  "diet_tags": {\n    "dinner.jpg": {\n      "meal": "dinner",\n      "source": "home"\n    }\n  }\n}',description:'以明确字段索引时间、媒体与餐别，使记录可以被筛选、统计和关联。'},links:{file:'event-links.json',status:'扩展设计 · 非现有功能',code:'{\n  "event": "晚餐",\n  "occurred_at": "2026-06-05T21:30",\n  "source": "2026-06-05.md",\n  "related": [\n    { "type": "sleep", "date": "2026-06-06" }\n  ],\n  "relation": "待验证的时间关联"\n}',description:'围绕事件连接不同维度，保留证据来源，并区分相关性与因果判断。'}};
function chooseNative(key,focus=false){const n=native[key];all('[data-native]').forEach(b=>{const active=b.dataset.native===key;b.setAttribute('aria-selected',String(active));b.tabIndex=active?0:-1;if(active&&focus)b.focus()});$('native-panel').setAttribute('aria-labelledby','native-'+key);$('native-filename').textContent=n.file;$('native-status').textContent=n.status;$('native-code').textContent=n.code;$('native-description').textContent=n.description}
const nativeTabs=all('[data-native]');nativeTabs.forEach((b,i)=>{b.addEventListener('click',()=>chooseNative(b.dataset.native));b.addEventListener('keydown',e=>{let j;if(['ArrowDown','ArrowRight'].includes(e.key))j=(i+1)%3;if(['ArrowUp','ArrowLeft'].includes(e.key))j=(i+2)%3;if(e.key==='Home')j=0;if(e.key==='End')j=2;if(j!==undefined){e.preventDefault();chooseNative(nativeTabs[j].dataset.native,true)}})});chooseNative('markdown');
$('recall-day').addEventListener('click',()=>{const on=$('recall-day').getAttribute('aria-expanded')!=='true';$('recall-day').setAttribute('aria-expanded',String(on));$('recall-day').innerHTML=(on?'合上那一天':'翻开那一天')+' <span aria-hidden="true">↗</span>';$('day-evidence').classList.toggle('is-recalled',on);const values=all('.recall-value');values[0].textContent=on?'晚餐较晚，食物偏油':'晚餐内容与发生时间';values[1].textContent=on?'当晚入睡困难，睡眠较差':'入睡时间与夜间状态';$('correlation-title').textContent=on?'晚餐与睡眠，可能存在怎样的关联？':'记忆会淡去，记录可以保留。';$('correlation-description').textContent=on?'这是我在生活中注意到的现象：晚饭吃得晚、偏油时，当晚更容易睡不好。长期对照饮食与睡眠记录，可以进一步验证这个观察。':'当饮食、睡眠、情绪与习惯进入同一条时间线，单个数据点就有了可以相互参照的上下文。'});
const agents={creative:{parts:['travel','photos','voice'],name:'创作 Agent',text:'连接经历、影像与表达，组织有上下文的个人作品。'},life:{parts:['sleep','habits'],name:'生活 Agent',text:'结合近期作息与习惯，提供有记录依据的生活建议。'},personal:{parts:['preferences','voice','habits'],name:'个人 Agent',text:'结合偏好、表达与日常习惯，协助安排符合个人需求的任务。'}};
const details={travel:'经历：旅行、地点与重要事件，关联当时的记录。',photos:'影像：照片与视频，关联拍摄时间和当天记录。',voice:'表达：文字、语音与想法，保留个人语言和观点。',sleep:'作息：入睡、起床与夜间状态，观察长期变化。',habits:'习惯：日常行动、目标与进展，呈现行为的连续性。',preferences:'偏好：从个人表达与已确认的选择中积累。'};
let agent='creative';const graph=$('constellation'),svg=graph.querySelector('svg');
function draw(){const r=graph.getBoundingClientRect();if(!r.width)return;svg.setAttribute('viewBox',`0 0 ${r.width} ${r.height}`);const center=el=>{const x=el.getBoundingClientRect();return[x.left-r.left+x.width/2,x.top-r.top+x.height/2]};const core=center($('person-core')),origin=center(graph.querySelector(`[data-network-agent="${agent}"]`));const path=(a,b,active)=>`<path class="${active?'active-line':''}" d="M ${a[0]} ${a[1]} C ${a[0]} ${(a[1]+b[1])/2}, ${b[0]} ${(a[1]+b[1])/2}, ${b[0]} ${b[1]}"/>`;svg.innerHTML=all('[data-context]').map(b=>path(core,center(b),false)+(agents[agent].parts.includes(b.dataset.context)?path(origin,center(b),true):'')).join('')}
function chooseAgent(key){agent=key;all('[data-network-agent]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.networkAgent===key)));all('[data-context]').forEach(b=>b.classList.toggle('linked',agents[key].parts.includes(b.dataset.context)));$('network-agent-name').textContent=agents[key].name;$('network-agent-result').textContent=agents[key].text;draw()}
all('[data-network-agent]').forEach(b=>b.addEventListener('click',()=>chooseAgent(b.dataset.networkAgent)));all('[data-context]').forEach(b=>b.addEventListener('click',()=>{all('[data-context]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));$('context-detail').textContent=details[b.dataset.context]}));new ResizeObserver(draw).observe(graph);chooseAgent('creative');
const software={collect:{image:'notebook',text:'多源信息按天归档，形成连续的个人数据资产。'},manage:{image:'journey',text:'按时间、主题与来源组织记录，保留可追溯的关联。'},analyze:{image:'sprout',text:'汇总生活指标，逐步发现值得验证的行为模式。'}};let mode='collect';function update(){const s=software[mode];$('software-art').src='assets/botanical-set/'+s.image+'.webp';$('software-description').textContent=s.text;$('ecosystem-detail').textContent='多源生活数据'+' → '+({collect:'按天归档，保留时间与来源。',manage:'连接相关记录，形成可检索的个人 context。',analyze:'对照长期变化，为个人 Agent 提供分析依据。'}[mode]);}
all('[data-software]').forEach(b=>b.addEventListener('click',()=>{mode=b.dataset.software;all('[data-software]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));update()}));
})();

(()=>{
 const steps={see:{label:'画面观察',text:'一条弯曲的步道穿过树林，路旁分布着花草与石头。',tags:['树林','步道','步道']},relate:{label:'上下文示例 · 来自当天日记',text:'“周末去郊外徒步，在林间停了一会儿。离开城市后，心情放松了很多。”',tags:['周末徒步','郊外','本人表达：放松']},index:{label:'一句话语义指纹',text:'周末郊外徒步时拍下的林间步道，是当天日记中让自己放松的一段行程。',tags:['可检索：林间徒步','可关联：旅行经历','可分析：活动与心情']}};
 const tabs=[...document.querySelectorAll('[data-fingerprint]')];
 function show(key,focus=false){const step=steps[key];tabs.forEach(b=>{const on=b.dataset.fingerprint===key;b.setAttribute('aria-selected',String(on));b.tabIndex=on?0:-1;if(on&&focus)b.focus()});document.getElementById('fingerprint-panel').setAttribute('aria-labelledby','fingerprint-tab-'+key);document.getElementById('fingerprint-label').textContent=step.label;document.getElementById('fingerprint-text').textContent=step.text;document.getElementById('fingerprint-tags').replaceChildren(...step.tags.map(t=>{const el=document.createElement('span');el.textContent=t;return el}));}
 tabs.forEach((b,i)=>{b.addEventListener('click',()=>show(b.dataset.fingerprint));b.addEventListener('keydown',e=>{let n;if(e.key==='ArrowRight')n=(i+1)%3;if(e.key==='ArrowLeft')n=(i+2)%3;if(e.key==='Home')n=0;if(e.key==='End')n=2;if(n!==undefined){e.preventDefault();show(tabs[n].dataset.fingerprint,true)}})});
})();
